#! python3
# -*- coding:utf-8 -*-
import requests
from bs4 import BeautifulSoup

r = requests.get('http://gihyo.jp/lifestyle/clip/01/everyday-cat')
soup = BeautifulSoup(r.content, 'html.parser')
title = soup.title #タイトルタグの情報を取得
type(title) #タグ型
print(title)
print(title.text)
