#! python3
#-*- encoding:utf-8 -*-
print('代表的な組み込み関数')
print('len : リスト、ディクショナリ、文字列などの要素数を返却。')
print('dict :dictオブジェクト生成')
print('list :listオブジェクト生成')
print('tuple :tupleオブジェクト生成')
print('set :setオブジェクト生成')
print('dir :現在のスコープの名前リスト、もしくはオブジェクト内の名前リストを返す。')
print('filter: 反復可能なオブジェクトのうち、条件にマッチするもののみを取得する。')
print('map :反復可能なオブジェクトの各要素に関数を適用した結果を返す。')
print('max :反復可能なオブジェクトの最大値を返す。')
print('min :反復可能なオブジェクトの最小値を返す。')
print('range :数列のシーケンスを得る。for文を指定回数繰り返す場合などによく使う。')
print('open :ファイルを開いてファイルオブジェクトを取得する。')
print('type :オブジェクトの型を取得する。')
print('reversed :シーケンスを逆順にしたオブジェクトを取得する。')
print('repr :オブジェクトを読みやすい文字列にして返す。')
print('input :標準入力から入力された値を返す')
