#! python3
# -*- coding:utf-8 -*-

import sys
from PIL import Image
from pathlib import Path

class ImgExpansion():
    def __init__(self, pathStr):
        if pathStr != None:
            imgPath = Path(pathStr)
            hasImgFile = False

            for imgName in imgPath.iterdir():
                if imgName.suffix == '.jpg' or imgName.suffix == '.jpeg':
                    print(str(imgName))
                    if hasImgFile == False:
                        hasImgFile = True
                        expandDir = Path(str(imgPath.absolute()) + "/expand")
                        expandDir.mkdir(parents=True,exist_ok=True)
                    
                    imgOrigin = Image.open(str(imgName))
                    for i in range(20,360,20):
                        imgSpinned = imgOrigin.rotate(i)
                        #imgSpinned.show()
                        imgSpinnedName = str(imgName.stem) + "_" + str(i) + "angle" + str(imgName.suffix)
                        imgSpinned.save(str(expandDir) + '/' + imgSpinnedName)
        else:
            print("no input directory")
            

if __name__ == '__main__':
    ImgExpansion(sys.argv[1])